apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "notifier.name" . }}
  labels:
    {{- include "notifier.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "notifier.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "notifier.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.global.helmLibrary }}
      securityContext:
        {{- include "helm-library.podSecurityContext" . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        {{- if .Values.image.pullSecret }}
        {{- range .Values.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- else }}
        {{- range .Values.global.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository | default .Values.global.image.repository }}/elma365/notifier/notifier:{{ .Values.images.notifier }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.global.grpc_port }}
            - name: http
              containerPort: {{ .Values.global.http_port }}
          env:
            {{- if .Values.appconfig.push.fcmKey }}
            - name: ELMA365_FCM_CREDENTIALS_PATH
              value: {{ .Values.appconfig.push.keyPath | quote }}
            {{- end }}
            - name: ELMA365_NAMESPACE
              value: {{ default .Release.Namespace .Values.namespace }} # для редиса
            - name: ELMA365_ITEM_UPDATED_CONCURRENCY_COUNT
              value: {{ .Values.appconfig.itemUpdatedConcurrencyCount | quote }}
            - name: ELMA365_OBSERVABLE_COLLECTION_EVENTS_CONCURRENCY_COUNT
              value: {{ .Values.appconfig.observableCollectionEventsConcurrencyCount | quote }}
            - name: ELMA365_PUSH_PROTOCOL
              value: {{ .Values.appconfig.pushProtocol | quote }}
          envFrom:
            - configMapRef:
                name: elma365-env-config
                optional: true
            - secretRef:
                name: elma365-db-connections
                optional: true
          livenessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.global.http_port }}
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.global.http_port }}
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
      {{- if .Values.global.helmLibrary }}
          {{- include "helm-library.deployment.resources" . | indent 10 }}
          {{- include "helm-library.deployment.volumeMounts-notifier" . | indent 10 }}
        {{- include "helm-library.deployment.volumes-notifier" . | indent 6 }}
        {{- include "helm-library.deployment.terminationgraceperiod" . | indent 6 }}
        {{- include "helm-library.deployment.scheduling" . | indent 6 }}
      {{- end }}
