# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: notifier
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "notifier.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.appconfig.push.fcmKey }}
  FCM_KEY: {{ .Values.appconfig.push.fcmKey | b64enc |  quote }}
  {{- end }}
