{{- if .Values.global.secretCreationHook }}

apiVersion: batch/v1
kind: Job
metadata:
  name: create-db-connections-secret
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-28"
spec:
  backoffLimit: {{ .Values.global.backoffLimit }}
  {{- if .Values.global.setupJobTtlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.global.setupJobTtlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      name: create-db-connections-secret
      labels:
        sidecar.istio.io/inject: "false"
      annotations:
        linkerd.io/inject: disabled
    spec:
      serviceAccountName: internal-kubectl-secrets
      imagePullSecrets:
      {{- range .Values.global.image.pullSecret }}
        - name: {{ . }}
      {{- end }}
      containers:
      - name: create-db-connections-secret
        image: "{{ .Values.global.image.repository }}/docker/toolkit/kubectl:1.25.13-debian-11-r17"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command: ["sh", "-c", "env | grep -E '*_URL|S3_*' > /tmp/secrets.txt && kubectl create secret generic elma365-db-connections --save-config --dry-run=client --from-env-file=/tmp/secrets.txt -o yaml | kubectl apply -f -"]
        env:
        {{- with .Values.db }}
        - name: PSQL_URL
          value: {{ default "" .psqlUrl   | quote }}
        - name: RO_POSTGRES_URL
          value: {{ default "" .roPsqlUrl | quote }}
        - name: ELMA365_POOL_POSTGRES_URL
          value: {{ default "" .roPsqlUrl | quote }}
        - name: MONGO_URL
          value: {{ default "" .mongoUrl  | quote }}
        - name: AMQP_URL
          value: {{ default "" .amqpUrl   | quote }}
        - name: REDIS_URL
          value: {{ default "" .redisUrl  | quote }}
        - name: VAHTER_MONGO_URL
          value: {{ default "" .vahterMongoUrl | quote }}
        {{- with .s3 }}
        - name: S3_BACKEND_ADDRESS
          value: {{ .backend.address | quote }}
        - name: S3_REGION
          value: {{ .backend.region | quote }}
        - name: S3_BUCKET
          value: {{ .bucket | quote }}
        - name: S3_KEY
          value: {{ .accesskeyid | quote }}
        - name: S3_SECRET
          value: {{ .secretaccesskey | quote }}
        - name: S3_SSL_ENABLED
          value: {{ .ssl.enabled | quote }}
        - name: S3_UPLOAD_METHOD
          value: {{ .method | quote }}
        - name: S3_DUMP_URL
          value: {{ default "" .dumpurl | quote }}
        - name: S3_INTERCLUSTER_BUCKET
          value: {{ default "" .interclusterbucket | quote }}
        {{- end }}
        {{- end }}
        volumeMounts:
        - name: secret-volume
          mountPath: /tmp
      volumes:
      - name: secret-volume
        emptyDir: {}
      restartPolicy: OnFailure

{{- end }}
