{{- if .Values.global.secretCreationHook }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-30"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-30"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","update","create","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-secrets-to-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-30"
subjects:
  - kind: ServiceAccount
    name: internal-kubectl-secrets
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: modify-secrets
  apiGroup: rbac.authorization.k8s.io

{{- end }}
