pyroscope:
  storage:
    type: s3
    s3:
      bucket: "pyroscope"
      endpoint: "master.sale.elewise.com:9000"
      insecure: false  # Включаем TLS
      existingSecret: "pyroscope-s3-creds"  # Secret с access_key/secret_key
      tls:
        enabled: true
  alloy:
    config: |
      logging {
        level = "info"
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }

      discovery.relabel "elma_pods" {
        targets = discovery.kubernetes.pods.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          regex         = "elma365|elma365-dbs"
          action        = "keep"
        }

        # CPU profile
        rule {
          source_labels = ["__meta_kubernetes_pod_annotation_profiles_grafana_com_cpu_scrape"]
          regex         = "true"
          action        = "keep"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_annotation_profiles_grafana_com_cpu_port"]
          target_label  = "__param_port"
          action        = "replace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_annotation_profiles_grafana_com_cpu_path"]
          target_label  = "__param_path"
          action        = "replace"
        }

        rule {
          target_label  = "__param_profile_type"
          replacement   = "cpu"
          action        = "replace"
        }

        rule {
          source_labels = ["__address__", "__param_port"]
          separator     = ":"
          target_label  = "__address__"
          action        = "replace"
          replacement   = "$1:$2"
        }
      }

      discovery.relabel "elma_memory" {
        targets = discovery.kubernetes.pods.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          regex         = "elma365|elma365-dbs"
          action        = "keep"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_annotation_profiles_grafana_com_memory_scrape"]
          regex         = "true"
          action        = "keep"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_annotation_profiles_grafana_com_memory_port"]
          target_label  = "__param_port"
          action        = "replace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_annotation_profiles_grafana_com_memory_path"]
          target_label  = "__param_path"
          action        = "replace"
        }

        rule {
          target_label  = "__param_profile_type"
          replacement   = "heap"
          action        = "replace"
        }

        rule {
          source_labels = ["__address__", "__param_port"]
          separator     = ":"
          target_label  = "__address__"
          action        = "replace"
          replacement   = "$1:$2"
        }
      }

      discovery.relabel "elma_goroutine" {
        targets = discovery.kubernetes.pods.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          regex         = "elma365|elma365-dbs"
          action        = "keep"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_annotation_profiles_grafana_com_goroutine_scrape"]
          regex         = "true"
          action        = "keep"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_annotation_profiles_grafana_com_goroutine_port"]
          target_label  = "__param_port"
          action        = "replace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_annotation_profiles_grafana_com_goroutine_path"]
          target_label  = "__param_path"
          action        = "replace"
        }

        rule {
          target_label  = "__param_profile_type"
          replacement   = "goroutine"
          action        = "replace"
        }

        rule {
          source_labels = ["__address__", "__param_port"]
          separator     = ":"
          target_label  = "__address__"
          action        = "replace"
          replacement   = "$1:$2"
        }
      }

      profiling.scrape "elma_cpu" {
        targets = discovery.relabel.elma_pods.output
        forward_to = [profiling.write.pyro.receiver]
      }

      profiling.scrape "elma_memory" {
        targets = discovery.relabel.elma_memory.output
        forward_to = [profiling.write.pyro.receiver]
      }

      profiling.scrape "elma_goroutine" {
        targets = discovery.relabel.elma_goroutine.output
        forward_to = [profiling.write.pyro.receiver]
      }

      profiling.write "pyro" {
        endpoint {
          url = "http://pyroscope.pyroscope.svc.cluster.local:4040"
        }
      }