pyroscope:
  storage:
    type: s3
    s3:
      bucket: "pyroscope"
      endpoint: "master.sale.elewise.com:9000"
      insecure: false  # Включаем TLS
      existingSecret: "pyroscope-s3-creds"  # Secret с access_key/secret_key
      tls:
        enabled: true
alloy:
  enabled: true
  # Creating a configmap for Pyroscope Alloy integration
  configMap:
    create: true
    name: pyroscope-alloy-config
    content: |
      logging {
        level  = "info"
        format = "logfmt"
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }

      discovery.relabel "elma" {
        targets = discovery.kubernetes.pods.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          regex         = "elma365|elma365-dbs"
          action        = "keep"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_label_app"]
          regex         = ".*"
          action        = "keep"
        }

        rule {
          target_label  = "__param_profile_type"
          replacement   = "cpu"
          action        = "replace"
        }

        rule {
          target_label  = "__param_path"
          replacement   = "/debug/pprof/profile"
          action        = "replace"
        }

        rule {
          target_label  = "__param_port"
          replacement   = "8080"
          action        = "replace"
        }

        rule {
          source_labels = ["__address__", "__param_port"]
          separator     = ":"
          target_label  = "__address__"
          action        = "replace"
          replacement   = "$1:$2"
        }
      }

      profiling.scrape "elma_profiles" {
        targets = discovery.relabel.elma.output
        forward_to = [profiling.write.to_pyroscope.receiver]
      }

      profiling.write "to_pyroscope" {
        endpoint {
          url = "http://pyroscope.pyroscope.svc.cluster.local:4040"
        }
      }