apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elma365
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LovemeTrue/ArgoCI-CD.git
    targetRevision: main
    path: elma365-appsets/apps/elma365
    helm:
      chart: elma365
      repoURL: https://charts.elma365.tech
      valueFiles:
        - values-elma365.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: elma365
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
