global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels: {event-producer: "true"}
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    rabbitmqQueueLength: 500
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
  setupJobTtlSecondsAfterFinished:
images:
  service: ci-e69fca04
  setup: ci-0f43fdf5
image:
  repository: {}
  pullSecret: {}
nameOverride: processor
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
kubeVersion: ""
autoscaling: {}
resourcesJobs: {}
resources:
  requests:
    memory: "400Mi"
    cpu: "300m"
  limits:
    memory: "1536Mi"
    cpu: "1500m"
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
appconfig:
  runLimitSubProcesses: 4
  runLimitToRestoreProcesses: 4
  outdatedProcessesThresholdHours: 60
  customActivityScriptMinCheckInterval: "1m"
annotations:
  ci.elma365.com/commit: "38175527"
  ci.elma365.com/checksum: "0f43fdf5"
  ci.elma365.com/job_id: "3294666"
  ci.elma365.com/timestamp: "2025-06-02T10:37:24+00:00"
  ci.elma365.com/pipeline_id: "585503"
