global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
images:
  service: ci-eb4f6d1f
image:
  repository: {}
  pullSecret: {}
autoscaling: {}
fullnameOverride: scheduler
nameOverride: scheduler
podAnnotations: {}
podSecurityContext: {}
resourcesJobs: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
annotations:
  ci.elma365.com/commit: "0455a142"
  ci.elma365.com/checksum: "eb4f6d1f"
  ci.elma365.com/job_id: "1946067"
  ci.elma365.com/timestamp: "2024-02-13T18:09:36+04:00"
  ci.elma365.com/pipeline_id: "386108"
