global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  client_http_port: 3001
  replicaCount: 1
  updateStrategy:
    type: Recreate
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  startupProbe:
    httpGet:
      path: /healthz
      port: http
    failureThreshold: 180
    periodSeconds: 10
  podSecurityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
images:
  service: ci-9753d35c
  client: ci-f0aca3d3
image:
  repository: {}
  pullSecret: {}
appconfig:
  httpTimeout: 1m
nameOverride: messenger-whatsapp
podSecurityContext: {}
podAnnotations: {}
autoscaling: {}
resourcesJobs: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
annotations:
  ci.elma365.com/commit: "dca4ad52"
  ci.elma365.com/checksum: "9753d35c"
  ci.elma365.com/job_id: "2192238"
  ci.elma365.com/timestamp: "2024-05-21T13:39:51+00:00"
  ci.elma365.com/pipeline_id: "424393"
