{{- if eq .Values.global.solution "saas2" -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "worker.name" . }}-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "worker.name" . }}
  policyTypes:
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - podSelector:
            matchLabels:
              app: {{ include "gateway.name" . }}
      ports:
        - port: {{ .Values.global.http_port }}
        - port: {{ .Values.global.grpc_port }}
    - to:
        - namespaceSelector: {}
          podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                - rabbitmq
                - rabbitmq-ha
      ports:
        - port: 5672
        - port: 15672
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
        - port: 5672
        - port: 15672
{{- end }}
