# JWT secret
kind: Secret
apiVersion: v1
type: tls
data:
  tls.key: {{ .Values.secrets.tls.key | b64enc }}
  tls.crt: {{ .Values.secrets.tls.cert | b64enc }}
metadata:
  name: vahter-jwt
  labels:
    {{- include "vahter.labels" . | nindent 4 }}
