{{- define "helm-library.deployment.scheduling" }}
{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- with .Values.global.nodeSelector }}
nodeSelector:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.global.tolerations }}
tolerations:
{{- toYaml . | nindent 2 }}
{{- end }}
affinity:
{{- with $.Values.global.affinity }}
{{- toYaml . | nindent 2 }}
{{- else }}
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - {{ $name }}
              - key: release
                operator: In
                values:
                  - "{{ .Release.Name }}"
          topologyKey: kubernetes.io/hostname
        weight: 10
{{- end }}
{{- end }}

{{- define "helm-library.deployment.scheduling-billing" }}
{{- $name := include "helm-library.name" . }}
{{- with .Values.global.nodeSelector }}
nodeSelector:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- if .Values.tolerations }}
{{- with .Values.tolerations }}
tolerations:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- else if eq .Values.global.solution "onPremise" }}
tolerations:
- effect: NoSchedule
  operator: Exists
{{- else }}
{{- with .Values.global.tolerations }}
tolerations:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
affinity:
{{- with .Values.global.affinity }}
{{- toYaml . | nindent 2 }}
{{- else }}
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - {{ $name }}
              - key: release
                operator: In
                values:
                  - "{{ .Release.Name }}"
          topologyKey: kubernetes.io/hostname
        weight: 10
{{- end }}
{{- end }}
