{{- if and (.Values.alloy.enabled) (not .Values.alloy.alloy.configMap.create)  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-alloy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
data:
  config.alloy: |
    {{ .Files.Get "alloy.conf" | indent 4 }}