{{- if and (.Values.alloy.enabled) (not .Values.alloy.alloy.configMap.create)  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alloy.alloy.configMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
data:
  data:
  config.alloy: |
    logging {
      level = "info"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    discovery.relabel "my_apps" {
      targets = discovery.kubernetes.pods.targets

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        regex         = "elma365|elma365-dbs"
        action        = "keep"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_app"]
        regex         = ".*"
        action        = "keep"
      }

      rule {
        target_label  = "__param_profile_type"
        replacement   = "cpu"
        action        = "replace"
      }

      rule {
        target_label  = "__param_port"
        replacement   = "8080"
        action        = "replace"
      }

      rule {
        target_label  = "__param_path"
        replacement   = "/debug/pprof/profile"
        action        = "replace"
      }

      rule {
        source_labels = ["__address__", "__param_port"]
        separator     = ":"
        target_label  = "__address__"
        action        = "replace"
        replacement   = "$1:$2"
      }
    }

    profiling.scrape "pyroscope" {
      targets = discovery.relabel.my_apps.output
      forward_to = [profiling.write.pyro.receiver]
    }

    profiling.write "pyro" {
      endpoint {
        url = "http://pyroscope.pyroscope.svc.cluster.local:4040"
      }
    }