---
- name: Добавление записей в /etc/hosts (с sudo паролем)
  hosts: master
  gather_facts: no
  vars:
    domains:
      - api.d8-multinode.sale.elewise.com
      - argocd.d8-multinode.sale.elewise.com
      - dashboard.d8-multinode.sale.elewise.com
      - documentation.d8-multinode.sale.elewise.com
      - dex.d8-multinode.sale.elewise.com
      - grafana.d8-multinode.sale.elewise.com
      - hubble.d8-multinode.sale.elewise.com
      - istio.d8-multinode.sale.elewise.com
      - istio-api-proxy.d8-multinode.sale.elewise.com
      - kubeconfig.d8-multinode.sale.elewise.com
      - openvpn-admin.d8-multinode.sale.elewise.com
      - prometheus.d8-multinode.sale.elewise.com
      - status.d8-multinode.sale.elewise.com
      - upmeter.d8-multinode.sale.elewise.com

  tasks:
    - set_fact:
        public_ip: "{{ hostvars['master']['ansible_host'] }}"

    - name: Добавить каждую запись в /etc/hosts
      ansible.builtin.shell: |
        grep -q "{{ item }}" /etc/hosts || echo "{{ public_ip }} {{ item }}" | sudo tee -a /etc/hosts > /dev/null
      loop: "{{ domains }}"
      loop_control:
        label: "{{ item }}"
      delegate_to: localhost
      become: yes
      become_method: sudo
      vars:
        ansible_become_password: "{{ lookup('password', 'Enter sudo password for localhost:') }}"