- name: Add system or worker nodes via NodeGroups
  hosts: master
  gather_facts: no
  vars_files:
    - ../vault.yml

  tasks:
    - name: Copy NodeGroup manifest
      template:
        src: ../templates/nodegroup-{{ node_role }}.yaml.j2
        dest: /root/{{ node_role }}.yaml

    - name: Apply NodeGroup
      shell: kubectl apply -f /root/{{ node_role }}.yaml

    - name: Fetch bootstrap script secret
      shell: |
        kubectl -n d8-cloud-instance-manager get secret manual-bootstrap-for-{{ node_role }} -o json | jq -r '.data."bootstrap.sh"' > /root/{{ node_role }}.b64

    - name: Decode bootstrap.sh
      shell: |
        base64 -d /root/{{ node_role }}.b64 > /root/{{ node_role }}.sh && chmod +x /root/{{ node_role }}.sh

    - name: Send and execute bootstrap script on nodes
      delegate_to: "{{ hostvars[item].ansible_host }}"
      become: true
      copy:
        src: /root/{{ node_role }}.sh
        dest: /tmp/bootstrap.sh
        mode: 0755
      loop: "{{ groups['cluster'] | difference(['master']) | select('match', node_role) | list }}"

    - name: Run bootstrap.sh on remote node
      delegate_to: "{{ hostvars[item].ansible_host }}"
      become: true
      shell: /tmp/bootstrap.sh
      loop: "{{ groups['cluster'] | difference(['master']) | select('match', node_role) | list }}"
