{{- $serviceName := include "billing.name" . }}
{{- $servicePort := .Values.global.http_port }}
{{- $host := .Values.global.host }}
{{- if eq .Values.global.solution "saas" }}
{{- if semverCompare ">=1.19-0" (include "kubeVersion" .) }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "billing.name" . }}
  labels:
    {{- include "billing.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.global.ingress.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.global.ingress.ingressClassName (include "billing.supportsIngressClassname" .) }}
  ingressClassName: {{ .Values.global.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
{{- if not .Values.global.companies }}
    - host: '{{ $host }}'
      http:
        paths:
          - path: /payment/tinkoff
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          - path: /payment/stripe
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
    - host: '*.{{ $host }}'
      http:
        paths:
          - path: /payment/tinkoff
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          - path: /payment/stripe
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- include "ingressTLS" (list . $host) | nindent 2 }}
{{- else }}
    {{- range $company := .Values.global.companies }}
    - host: '{{ $company }}.{{ $host }}'
      http:
        paths:
          - path: /payment/tinkoff
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          - path: /payment/stripe
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
    {{- end }}
  {{- $hosts := list }}
  {{- range $company := .Values.global.companies }}
  {{- $host := printf "%s.%s" $company $host }}
  {{- $hosts = append $hosts $host }}
  {{- end }}
  {{- include "ingressTLS" (list . $hosts) | nindent 2 }}
{{- end }}
---
{{- if eq .Values.global.edition "standard" }}
{{ if .Values.ingress.password }}
{{- if semverCompare ">=1.19-0" (include "kubeVersion" .) }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "billing.name" . }}-external
  labels:
    {{- include "billing.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /external/$2
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: billing
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.global.ingress.ingressClassName (include "billing.supportsIngressClassname" .) }}
  ingressClassName: {{ .Values.global.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
  {{- if not .Values.global.companies }}
    - host: '{{ $host }}'
      http:
        paths:
          - path: /billing/external(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
    - host: '*.{{ $host }}'
      http:
        paths:
          - path: /billing/external(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- include "ingressTLS" (list . .Values.global.host) | nindent 2 }}
  {{- else }}
    {{- range $company := .Values.global.companies }}
    - host: '{{ $company }}.{{ $host }}'
      http:
        paths:
          - path: /billing/external(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
    {{- end }}
  {{- $hosts := list }}
  {{- range $company := .Values.global.companies }}
    {{- $host := printf "%s.%s" $company $host }}
    {{- $hosts = append $hosts $host }}
  {{- end }}
  {{- include "ingressTLS" (list . $hosts) | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
