#Rabbitmq user
apiVersion: v1
kind: Secret
metadata:
  name: billing
  labels:
    {{- include "billing.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
type: Opaque
data:
  {{-  $serviceUniq := printf "%s-%s-%s" .Release.Namespace .Release.Name .Chart.Name }}
  rabbitmq_password: {{ default (trunc 16 ($serviceUniq | b64enc)) .Values.rabbitmq.password | b64enc | quote }}
  # пароль для ingress
  auth: {{ (print "apiuser:{PLAIN}" (index .Values.ingress.password)) | b64enc | quote }}
  # для лицензирования
  license_name: {{ .Values.appconfig.license.name | b64enc }}
  license_certificate: {{ .Values.appconfig.license.certificate | b64enc }}
