global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resources: {}
  resourceLimits: false
  resourcesJobs: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
images:
  service: ci-6a719261
image:
  repository: {}
  pullSecret: {}
nameOverride: picasso
podSecurityContext: {}
podAnnotations: {}
kubeVersion: ""
autoscaling: {}
resourcesJobs: {}
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "555Mi"
    cpu: "555m"
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
annotations:
  ci.elma365.com/commit: "379dc618"
  ci.elma365.com/checksum: "6a719261"
  ci.elma365.com/job_id: "2192614"
  ci.elma365.com/timestamp: "2024-05-21T16:09:32+00:00"
  ci.elma365.com/pipeline_id: "424448"
