{{- $serviceName := include "vahter.name" . -}}
{{- $servicePort := .Values.global.http_port -}}
{{- $paths := .Values.ingress.paths }}
{{- $host := .Values.global.host -}}
{{- if ne (toString .Values.global.openshift) "true" }}
{{- if semverCompare ">=1.19-0" (include "kubeVersion" .) -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "vahter.name" . }}
  labels:
    {{- include "vahter.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /public/$2
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  {{- if and .Values.global.ingress.ingressClassName (include "vahter.supportsIngressClassname" .) }}
  ingressClassName: {{ .Values.global.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
{{- if eq .Values.global.solution "onPremise" }}
  {{- if eq .Values.global.edition "hub" }}
    {{- range $index, $tenant := .Values.global.hub }}
    - host: '{{ $tenant.name }}.{{ $host }}'
      http:
        paths:
          {{- range $path := $paths }}
          - path: {{ $path }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end }}
    {{- end }}
  {{- if .Values.global.ingress.onpremiseTls.enabled }}
  tls:
    - hosts:
      {{- range $index, $tenant := .Values.global.hub }}
      - {{ $tenant.name }}.{{ $.Values.global.host }}
      {{- end }}
      secretName: {{ $.Values.global.ingress.onpremiseTls.secret }}
  {{- end }}
  {{- else }}

  {{- if or .Values.global.ingress.onpremiseTls.enabled .Values.global.ingress.hostEnabled }}
    - host: {{ .Values.global.host }}
      http:
  {{- else }}
    - http:
  {{- end }}
        paths:
          {{- range $path := $paths }}
          - path: {{ $path }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end }}
  {{- if .Values.global.ingress.onpremiseTls.enabled }}
  tls:
    - hosts:
      - {{ .Values.global.host }}
      secretName: {{ .Values.global.ingress.onpremiseTls.secret }}
  {{- end }}
  {{- end }}
{{- else }}
  {{- if not .Values.global.companies }}
    - host: {{ $host }}
      http:
        paths:
          {{- range $path := $paths }}
          - path: {{ $path }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end }}
    - host: '*.{{ $host }}'
      http:
        paths:
          {{- range $path := $paths }}
          - path: {{ $path }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end }}
  {{- include "ingressTLS" (list . $host) | nindent 2 }}
  {{- else }}
    {{- range $company := .Values.global.companies }}
    - host: '{{ $company }}.{{ $host }}'
      http:
        paths:
          {{- range $path := $paths }}
          - path: {{ $path }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" (include "kubeVersion" $) }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end }}
    {{- end -}}
  {{- $hosts := list }}
  {{- range $company := .Values.global.companies }}
    {{- $host := printf "%s.%s" $company $host }}
    {{- $hosts = append $hosts $host }}
  {{- end }}
  {{- include "ingressTLS" (list . $hosts) | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
