global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels:
    event-producer: "true"
  annotations: {}
  kubeVersion: ""
  ingress:
    annotations: {}
    ingressClassName: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
appconfig:
  featureFlags:
    ELMA365_FEATURE_FLAGS_ALLOW_PRIVATE_ROUTES_ACCESS: false
  saasEnabledFeatureFlags:
  onPremiseEnabledFeatureFlags:
    - extensionEventHandling
    - processEventHandling
    - delegatedEventHandling
    - appItemViewEventEnabled
    - fileDownloadEventEnabled
    - filePreviewEventEnabled
    - enableModuleServices
    - allowAttachWidgetFiles
    - useLegacyNodeVM
    - allowServerScriptsImport
    - enablePeriodicEvents
    - allowImportPortalUsersForAD
    - allowImportPortalUsersForLDAP
    - allowAuthPortalUsersWithSAML
    - allowEntityLocalization
    - enableDuplicateFTS
    - enableSQLPerformanceReport
    - enableInternalTelemetry
    - enableConvertPDFA1A
    - allowAttachExtensionScriptFiles
    - disableElementActivitiesStorageLimits
    - enableSubscriptionOnEventsFromScript
    - allowExternalApplicationsOIDC
    - enableNewWatermarkService
    - allowExternalApplicationsOIDC
    - allowScriptImportsDependencies
    - allowCustomActivityActionCall
    - enableNewCrmTasks
    - enableLowcodeCICD
  onPremiseCustomEnabledFeatureFlags: []
images:
  service: ci-735cfc02
image:
  repository: {}
  pullSecret: {}
ingress:
  enabled: false
  password: ''
  annotations: {}
nameOverride: settings
podAnnotations: {}
podSecurityContext: {}
kubeVersion: ""
resourcesJobs: {}
resources:
  requests:
    memory: "256Mi"
    cpu: "150m"
  limits:
    memory: "512Mi"
    cpu: "500m"
autoscaling: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
annotations:
  ci.elma365.com/commit: "9fba41cc"
  ci.elma365.com/checksum: "735cfc02"
  ci.elma365.com/job_id: "2159075"
  ci.elma365.com/timestamp: "2024-05-07T13:36:14+00:00"
  ci.elma365.com/pipeline_id: "418695"
