{{- define "helm-library.servicemonitor" }}
{{- $name := include "helm-library.name" . }}
{{- if eq (toString .Values.global.monitoring.enabled) "true" }}
{{- if ($.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: {{ $name }}
    {{- if eq (toString .Values.global.monitoring.provisioner) "deckhouse" }}
    prometheus: main
    {{- end }}
  name: {{ $name }}-servicemonitor
spec:
  endpoints:
  - port: http-metrics
    {{- if ne (toString .Values.global.monitoring.provisioner) "deckhouse" }}
    path: /metrics
    interval: {{ default "30s" .Values.global.monitoring.metrics.interval }}
    honorLabels: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    {{- end }}
    {{- if .Values.global.monitoring }}
    {{- if .Values.global.monitoring.metrics }}
    metricRelabelings:
      {{- if ne (toString .Values.global.monitoring.metrics.all) "true" }}
      - sourceLabels: [ __name__ ]
        regex: (elma365_common_cache_.+|elma365_common_redis_.+|elma365_common_postgresql_.+|rabbitmq_.+|.*_histogram_.*|.*_bucket)
        # regex: (elma365_common_cache_.+|elma365_common_redis_.+|elma365_common_postgresql_.+|rabbitmq_.+|eventbus_.+|.*_histogram_.*|.*_bucket)
        # regex: (elma365_common_redis_.+|elma365_common_postgresql_query_execution_time_histogram_.*|eventbus_delivery_duration_bucket|rabbitmq_.+) # worker_script_compile_time_histogram_bucket
        action: drop
      {{- end }}
      - targetLabel: region
        replacement: {{ printf "%s-%s-%s" .Release.Namespace .Values.global.solution .Values.global.edition }}
        action: replace
      - targetLabel: cluster
        replacement: {{ printf "%s" .Values.global.host | replace "." "-" | quote }}
        action: replace
    relabelings:
    - sourceLabels: [__name__]
      targetLabel: region
      replacement: {{ printf "%s" .Values.global.host | replace "." "-" | quote }}
    - sourceLabels: [__name__]
      targetLabel: cluster
      replacement: {{ printf "%s" .Values.global.host | replace "." "-" | quote }}
    {{- end }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ $name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
