{
 "title": "pod memory stats",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(go_memstats_heap_alloc_bytes, namespace)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(go_memstats_heap_alloc_bytes{namespace=~\"^($namespace)$\"}, container)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(go_memstats_heap_alloc_bytes{namespace=~\"^($namespace)$\", job=~\"^($job)$\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Count",
   "type": "heatmap",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(tpod) (label_replace(kube_pod_status_phase{cluster=\"yandex-ru\", exported_namespace=\"$namespace\", phase=\"Running\", exported_pod=~\"($job).*\", exported_pod!~\".*-ci-.*\"}, \"tpod\", \"$1\", \"exported_pod\", \"([a-zA-Z-]+)-([a-z0-9]+-[a-z0-9]+)\"))"
    }
   ]
  },
  {
   "title": "PG Max Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(container) (max by(prometheus_replica, container) (postgreSQL_max_connections))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory | GC | Terminate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "mem" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{job=~\"^($job)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}) by (pod)",
     "legendFormat": "MEM {{pod}}"
    }
   ]
  }
 ]
}