global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels: {}
  annotations: {}
  kubeVersion: ""
  ingress:
    annotations: {}
    ingressClassName: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 10
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: true
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: true
    alerts:
      enabled: false
    metrics:
      interval: 30s
  companies:
  cronStartingDeadlineSeconds: ""
  cronTtlSecondsAfterFinished: ""
  cronActiveDeadlineSeconds: ""
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  machineId: /etc/machine-id
  licenseV2: false
  setupJobTtlSecondsAfterFinished:
images:
  service: ci-5762ba01
  setup: ci-342415f0
image:
  repository: {}
  pullSecret: {}
nameOverride: billing
podSecurityContext: {}
podAnnotations: {}
kubeVersion: ""
resourcesJobs: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
tolerations: []
autoscaling: {}
appconfig:
  tinkoff:
    password: ""
  stripe:
    secret_key: ""
    webhook_secret: ""
  email: money@elma365.com
  license:
    name: FOO
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIBzjCCAXSgAwIBAgIUCmoZduVorAbWQalshHGC3HKOl98wCgYIKoZIzj0EAwIw
      HzEdMBsGA1UEAxMUZWxtYTM2NS10bHMtaW5qZWN0b3IwHhcNMjAxMDAxMDY0NDAw
      WhcNMzAwOTI5MDY0NDAwWjAfMR0wGwYDVQQDExRlbG1hMzY1LXRscy1pbmplY3Rv
      cjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLJgiSEgEmOsxvtvyRhFkbpEqKaj
      dktd53XOrVww7EgaV1nfA+XDsNmMceJ2RtCPIU2rkFRXdKcWWyk7xUABVi+jgY0w
      gYowDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFNHSDi69
      yKvdNBGDGlXHxosvurX6MEsGA1UdEQREMEKCHWVsbWEzNjUtdGxzLWluamVjdG9y
      LndlYmhvb2tzgiFlbG1hMzY1LXRscy1pbmplY3Rvci53ZWJob29rcy5zdmMwCgYI
      KoZIzj0EAwIDSAAwRQIhAJb8nt7DFO82n3KhTtYoRHhg/l31J+RaKWREb5jNZpu7
      AiADIGxoFMOwjTMUSon7wGbvXy+vdfKp6lb+AJikcz2jtA==
      -----END CERTIFICATE-----
  serviceRetry:
    retryTimeoutDuration: "60s"
    retryIntervalDuration: "5s"
ingress:
  annotations: {}
  password: ''
rabbitmq:
  vhName: {}
annotations:
  ci.elma365.com/commit: "5c8201b6"
  ci.elma365.com/checksum: "342415f0"
  ci.elma365.com/job_id: "2151144"
  ci.elma365.com/timestamp: "2024-05-06T06:12:54+00:00"
  ci.elma365.com/pipeline_id: "417480"
