{{- if eq .Values.global.solution "saas" -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "worker.name" . }}-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "worker.name" . }}
  policyTypes:
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    {{- if .Values.networkPolicy.allowIPLocalDns }}
    - to:
        {{- range .Values.networkPolicy.allowIPLocalDns }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
    {{- end }}
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    {{- if .Values.networkPolicy.allowIngressLabel }}
    {{- range $k,$v := .Values.networkPolicy.allowIngressLabel }}
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              {{ $k }}: {{ $v | quote }}
      ports:
        - port: 80
        - port: 443
    {{- end }}
    {{- end }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace | quote }}
          podSelector:
            matchExpressions:
              - key: tier
                operator: NotIn
                values:
                - elma365
    {{- if .Values.networkPolicy.allowNamespaceName }}
    {{- range .Values.networkPolicy.allowNamespaceName }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
          podSelector:
            matchExpressions:
              - key: tier
                operator: NotIn
                values:
                - elma365
    {{- end }}
    {{- end }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ include "gateway.name" . }}
      ports:
        - port: {{ .Values.global.http_port }}
        - port: {{ .Values.global.grpc_port }}
    - to:
        - namespaceSelector: {}
          podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                - rabbitmq
                - rabbitmq-ha
      ports:
        - port: 5672
        - port: 15672
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
            {{- range .Values.networkPolicy.allowAllIPexcept }}
            - {{ . }}
            {{- end }}
{{- end }}
