{{- $name := include "worker.name" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "worker.name" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-port-wrk
      port: {{ .Values.service.http_port_wrk }}
      targetPort: http-port-wrk
      protocol: TCP
    - name: http-metrics
      port: {{ .Values.global.http_metrics }}
      targetPort: http-port-wrk
      protocol: TCP
  selector:
    {{- include "worker.selectorLabels" . | nindent 4 }}
