{{- if and (eq .Values.global.solution "saas") (eq .Values.global.edition "standard") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "intercluster.name" . }}
  labels:
    {{- include "intercluster.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.global.grpc_port }}
      targetPort: grpc
      protocol: TCP
    - name: http
      port: {{ .Values.global.http_port }}
      targetPort: http
      protocol: TCP
    - name: http-metrics
      port: {{ .Values.global.http_metrics }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "intercluster.selectorLabels" . | nindent 4 }}
{{- end }}
