{
 "title": "RabbitMQ Overview",
 "description": "Rabbitmq stats and alerting using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=~\".*rabbitmq-exporter.*\"},region)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(rabbitmq_running{region=\"$cluster\"}, node)"
    }
   },
   {
    "name": "vhost",
    "label": "vhost",
    "query": {
     "query": "label_values(rabbitmq_queue_messages_ready{region=\"$cluster\"},vhost)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(rabbitmq_running, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory limit Alarm",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_node_mem_alarm{node=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Disk limit Alarm",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_node_disk_free_alarm{node=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Instance Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (node) (rabbitmq_running{node=~\".*$node.*\",region=\"$cluster\"})",
     "legendFormat": "$node"
    }
   ]
  },
  {
   "title": "$node Used memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "repeat": "node",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rabbitmq_node_mem_used{node=~\".*$node.*\",region=\"$cluster\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum by (node) (rabbitmq_node_mem_limit{node=~\".*$node.*\",region=\"$cluster\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "$node Free disk space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "repeat": "node",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rabbitmq_node_disk_free{node=~\".*$node.*\",region=\"$cluster\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum by (node) (rabbitmq_node_disk_free_limit{node=~\".*$node.*\",region=\"$cluster\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Connections/Channels/Consumers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections, channels and consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_connectionsTotal{region=\"$cluster\"}",
     "legendFormat": "{{ job }} connections"
    },
    {
     "expr": "rabbitmq_channelsTotal{region=\"$cluster\"}",
     "legendFormat": "{{ job }} channels"
    },
    {
     "expr": "rabbitmq_consumersTotal{region=\"$cluster\"}",
     "legendFormat": "{{ job }} consumers"
    }
   ]
  },
  {
   "title": "Messages status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages status for vhost $vhost",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "repeat": "vhost",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (region,queue,vhost)(rate(rabbitmq_queue_messages_ready{region=\"$cluster\",vhost=\"$vhost\"}[5m]))",
     "legendFormat": "{{vhost}} | {{queue}}:ready"
    },
    {
     "expr": "sum by (region,queue,vhost)(rate(rabbitmq_queue_messages_published_total{region=\"$cluster\",vhost=\"$vhost\"}[5m]))",
     "legendFormat": "{{vhost}} | {{queue}}:published"
    },
    {
     "expr": "sum by (region,queue,vhost)(rate(rabbitmq_queue_messages_delivered_total{region=\"$cluster\",vhost=\"$vhost\"}[5m]))",
     "legendFormat": "{{vhost}} | {{queue}}:delivered"
    },
    {
     "expr": "sum by (region,queue,vhost)(rate(rabbitmq_queue_messages_unacknowledged{region=\"$cluster\",vhost=\"$vhost\"}[5m]))",
     "legendFormat": "{{vhost}} | {{queue}}:unack"
    }
   ]
  },
  {
   "title": "Messages per Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages per Queue for vhost $vhost",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "repeat": "vhost",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{region=\"$cluster\",vhost=\"$vhost\"}",
     "legendFormat": "{{vhost}} | {{queue}}"
    }
   ]
  }
 ]
}