{
 "title": "yandex-storage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "resource_id",
    "label": "bucket",
    "query": {
     "query": "label_values(objects_count{},resource_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Space by storage type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "space_usage{service=\"storage\", resource_id=~\"^($resource_id)$\", storage_type=\"StandardStorage\", resource_type=\"bucket\"}/2",
     "legendFormat": "{{storage_type}} - {{resource_id}}"
    },
    {
     "expr": "space_usage{service=\"storage\", resource_id=~\"^($resource_id)$\", storage_type=\"ColdStorage\", resource_type=\"bucket\"}/2",
     "legendFormat": "{{storage_type}} - {{resource_id}}"
    },
    {
     "expr": "space_usage{service=\"storage\", resource_id=~\"^($resource_id)$\", storage_type=\"IceStorage\", resource_type=\"bucket\"}/2",
     "legendFormat": "{{storage_type}} - {{resource_id}}"
    }
   ]
  },
  {
   "title": "Space by object type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "space_usage{service=\"storage\", resource_id=~\"^($resource_id)$\",resource_type=\"bucket\"}/2",
     "legendFormat": "{{object_type}} - {{resource_id}}"
    },
    {
     "expr": "max_size{service=\"storage\", resource_id=~\"^($resource_id)$\",resource_type=\"bucket\"}/2",
     "legendFormat": "max_size - {{resource_id}}"
    }
   ]
  },
  {
   "title": "Read Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rps{service=\"storage\", method=\"GetRequests\", resource_id=~\"^($resource_id)$\", resource_type=\"bucket\"}",
     "legendFormat": "{{ method}} - {{resource_id}}"
    },
    {
     "expr": "rps{service=\"storage\", resource_id=~\"^($resource_id)$\",method=\"HeadRequests\", resource_type=\"bucket\"}",
     "legendFormat": "{{ method}} - {{resource_id}}"
    },
    {
     "expr": "rps{service=\"storage\", resource_id=~\"^($resource_id)$\",method=\"ListRequests\", resource_type=\"bucket\"}",
     "legendFormat": "{{ method}} - {{resource_id}}"
    },
    {
     "expr": "rps{service=\"storage\", resource_id=~\"^($resource_id)$\",method=\"OptionsRequests\", resource_type=\"bucket\"}",
     "legendFormat": "{{ method}} - {{resource_id}}"
    }
   ]
  },
  {
   "title": "Modify Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rps{service=\"storage\", resource_id=~\"^($resource_id)$\",method=\"PutRequests\", resource_type=\"bucket\"}",
     "legendFormat": "{{ method}} - {{resource_id}}"
    },
    {
     "expr": "rps{service=\"storage\", resource_id=~\"^($resource_id)$\",method=\"PostRequests\", resource_type=\"bucket\"}",
     "legendFormat": "{{ method}} - {{resource_id}}"
    },
    {
     "expr": "rps{service=\"storage\", resource_id=~\"^($resource_id)$\",method=\"DeleteRequests\", resource_type=\"bucket\"}",
     "legendFormat": "{{ method}} - {{resource_id}}"
    }
   ]
  },
  {
   "title": "Objects counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "objects_count{service=\"storage\", resource_id=~\"^($resource_id)$\",resource_type=\"bucket\"}/1000000",
     "legendFormat": "{{object_type}} - {{resource_id}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "traffic{service=\"storage\", resource_id=~\"^($resource_id)$\",bytes=\"BytesDownloaded\", resource_type=\"bucket\"}",
     "legendFormat": "{{resource_type}} - {{resource_id}}"
    },
    {
     "expr": "traffic{service=\"storage\", resource_id=~\"^($resource_id)$\",bytes=\"BytesUploaded\", resource_type=\"bucket\"}",
     "legendFormat": "{{resource_type}} - {{resource_id}}"
    }
   ]
  }
 ]
}