{
 "title": "ELMA365-Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "query_result(up{job=~\"main\"})"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"node-exporter\",},instance)"
    }
   },
   { "name": "Loki", "label": "Loki", "query": "loki" },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values(process_start_time_seconds{namespace=\"$namespace\"}, deployment)"
    }
   },
   { "name": "searchable_pattern", "label": "Loki search text" }
  ]
 },
 "panels": [
  {
   "title": "ELMA365",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "APDEX - API - FRONT",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 105 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\r\n  sum(rate(front_api_request_duration_seconds_bucket{le=\"0.25\"}[5m])) by (company)\r\n+\r\n  sum(rate(front_api_request_duration_seconds_bucket{le=\"1\"}[5m])) by (company)\r\n) / 2 / sum(rate(front_api_request_duration_seconds_count[5m])) by (company) > 0",
       "legendFormat": "{{company}}"
      }
     ]
    },
    {
     "title": "APDEX - API - WORKER",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 105 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\r\n  sum(rate(worker_gateway_http_server_request_duration_seconds_bucket{le=\"0.25\"}[5m])) by (company)\r\n+\r\n  sum(rate(worker_gateway_http_server_request_duration_seconds_bucket{le=\"1\"}[5m])) by (company)\r\n) / 2 / sum(rate(worker_gateway_http_server_request_duration_seconds_count[5m])) by (company) > 0",
       "legendFormat": "{{company}}"
      }
     ]
    },
    {
     "title": "APDEX - SCRIPTS - WIDGET",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 105 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\r\n  sum(rate(worker_script_execution_time_histogram_bucket{le=\"2000\",source=\"widget\"}[5m])) by (company)\r\n+\r\n  sum(rate(worker_script_execution_time_histogram_bucket{le=\"10000\",source=\"widget\"}[5m])) by (company)\r\n) / 2 / sum(rate(worker_script_execution_time_histogram_count{source=\"widget\"}[5m])) by (company) > 0",
       "legendFormat": "{{company}}"
      }
     ]
    },
    {
     "title": "Scripts Queue",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages{queue=\"script.default\"}) by (queue)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Front Api Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "sum by(company) (increase(front_api_requests_total{}[5m])) > 0",
       "legendFormat": "{{company}} - front"
      },
      {
       "expr": "sum by(company) (increase(worker_gateway_http_server_requests_total{}[5m])) > 0",
       "legendFormat": "{{company}} - worker-gateway"
      }
     ]
    },
    {
     "title": "Script Execution Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(worker_script_execution_time_histogram_bucket{}[$__rate_interval])) by (le, company, source)) > 0",
       "legendFormat": "{{company}} - {{source}}"
      }
     ]
    },
    {
     "title": "Front API Req Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, company) (rate(front_api_request_duration_seconds_bucket[$__rate_interval]))) > 0",
       "legendFormat": "{{company}} - front"
      }
     ]
    },
    {
     "title": "Scripts Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
     "targets": [
      {
       "expr": "sum by(company, source) (increase(worker_execute_scripts_total{}[5m])) > 0",
       "legendFormat": "{{company}} - {{source}}"
      }
     ]
    },
    {
     "title": "Web Api Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 123 },
     "targets": [
      {
       "expr": "sum by(company) (increase(web_api_http_server_requests_total{}[5m])) > 0",
       "legendFormat": "{{company}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ELMA365 - Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scripts Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(10, histogram_quantile(0.95, sum by(le, elma365_script_function_name) (rate(elma365_telemetry_script_execution_duration_milliseconds_bucket[$__rate_interval])))) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP Req Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(3, histogram_quantile(0.95, sum by(le, http_route) (rate(elma365_telemetry_http_request_duration_milliseconds_bucket[10m]))) > 0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "topk(10, sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"^($namespace)$\"}) by (pod))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "topk(10, rate(container_cpu_usage_seconds_total{namespace=~\"^($namespace)$\"}[15m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage (w/o cache)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(node_namespace_pod_container:container_memory_working_set_bytes{container!=\"\", namespace=~\"^($namespace)$\"}) by (pod))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "topk(10, container_memory_usage_bytes{container!=\"\", namespace=~\"^($namespace)$\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Autoscaling",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"^($namespace)$\"})",
       "legendFormat": "{{horizontalpodautoscaler}}"
      }
     ]
    },
    {
     "title": "Pods Health",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum(kube_pod_info{namespace=~\"^($namespace)$\"})",
       "legendFormat": "Pods Count"
      }
     ]
    },
    {
     "title": "Pods Status",
     "type": "stat",
     "gridPos": { "h": 10, "w": 17, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
     "targets": [
      {
       "expr": "kube_pod_status_phase{phase!~\"Running|Succeeded\", namespace=~\"^($namespace)$\"} > 0 or kube_pod_status_phase{phase=~\"Running|Succeeded\", namespace=~\"^($namespace)$\"} > 0 ",
       "legendFormat": "{{ pod }} - {{ phase }}"
      }
     ]
    },
    {
     "title": "Pods Status",
     "type": "table",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 26 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{phase!~\"Running|Succeeded\", namespace=~\"^($namespace)$\"} > 0",
       "legendFormat": "{{ pod }} - {{ phase }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|steal\", instance=~\"^($instance)$\"}[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=~\"^($instance)$\"})\n) by (instance)\n",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"^($instance)$\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=~\"^($instance)$\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=~\"^($instance)$\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=~\"^($instance)$\"}\n)\n",
       "legendFormat": "memory used {{instance}}"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 115 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{job=\"node-exporter\", instance=~\"^($instance)$\"}",
       "legendFormat": "1m load average {{instance}}"
      },
      {
       "expr": "node_load5{job=\"node-exporter\", instance=~\"^($instance)$\"}",
       "legendFormat": "5m load average {{instance}}"
      },
      {
       "expr": "node_load15{job=\"node-exporter\", instance=~\"^($instance)$\"}",
       "legendFormat": "15m load average {{instance}}"
      },
      {
       "expr": "count(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=~\"^($instance)$\"})",
       "legendFormat": "logical cores {{instance}}"
      }
     ]
    },
    {
     "title": "Network Received",
     "type": "graph",
     "description": "Network received (bits/s)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 115 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{job=\"node-exporter\", device!=\"lo\", instance=~\"^($instance)$\"}[$__rate_interval]) * 8) by (instance)",
       "legendFormat": "receive {{instance}}"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{job=\"node-exporter\", device!=\"lo\", instance=~\"^($instance)$\"}[$__rate_interval]) * 8) by (instance)",
       "legendFormat": "transmit {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Space Usage",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{fstype!=\"\", mountpoint=\"/\", instance=~\"^($instance)$\"}\n"
      },
      {
       "expr": "node_filesystem_avail_bytes{fstype!=\"\", mountpoint=\"/\", instance=~\"^($instance)$\"}\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "label_replace(pg_static{}, \"server\", \"${1}\", \"server\", \"(.*?)(\\\\.rw\\\\.mdb\\\\.yandexcloud\\\\.net:6432|\\\\.svc\\\\.cluster\\\\.local)$\")",
       "legendFormat": "{{server}} - {{short_version}}"
      }
     ]
    },
    {
     "title": "DB Size",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 5, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_database_size_bytes{datname!~\"postgres|template.*\",}) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Stat activity",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{} !=0) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(avg(pg_settings_max_connections{}) by (server), \"server\", \"${1}\", \"server\", \"(.*?)(\\\\.rw\\\\.mdb\\\\.yandexcloud\\\\.net:6432|\\\\.svc\\\\.cluster\\\\.local)$\")",
       "legendFormat": "{{server}} - "
      }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total queues",
     "type": "timeseries",
     "description": "Total number of queue master replicas per node. \n\nThis metric makes it easy to see sub-optimal queue distribution in a cluster.\n\n* [Queue Masters, Data Locality](https://www.rabbitmq.com/ha.html#master-migration-data-locality)\n* [Queues](https://www.rabbitmq.com/queues.html)",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 142 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rabbitmq_queuesTotal{}", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Channels",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rabbitmq_channelsTotal{}" }
     ]
    },
    {
     "title": "Total consumers",
     "type": "timeseries",
     "description": "Total number of consumers master replicas per node. \n\nThis metric makes it easy to see sub-optimal queue distribution in a cluster.\n\n* [Queue Masters, Data Locality](https://www.rabbitmq.com/ha.html#master-migration-data-locality)\n* [Queues](https://www.rabbitmq.com/queues.html)",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 142 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rabbitmq_consumersTotal{}", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Connections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rabbitmq_connectionsTotal{}" }
     ]
    },
    {
     "title": "Messages per Queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 148 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages) by (queue)",
       "legendFormat": "{{queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 143 },
     "yaxes": [
      { "format": "decmbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "mongodb_memory{type=~\"resident|virtual\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "stat",
     "gridPos": { "h": 13, "w": 2, "x": 11, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mongodb_connections{state=\"current\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 143 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_op_counters_total{}[15m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Queries Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      { "expr": "mongodb_top_queries_time{}", "legendFormat": "{{collection}}" }
     ]
    },
    {
     "title": "Update Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      { "expr": "mongodb_top_update_time{}", "legendFormat": "{{collection}}" }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      { "expr": "redis_cpu_user_seconds_total{}", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      { "expr": "redis_memory_used_bytes{}", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Total Commands / sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_commands_total{} [1m])) by (cmd)",
       "legendFormat": "{{ cmd }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingress Certificate Expiry",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 145 },
     "targets": [
      {
       "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{}) by (host) - time()",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "HTTP Rate",
     "type": "graph",
     "description": "The breakdown of the various HTTP status codes of the requests handled within' this period that matches the variables chosen above.\n\nThis chart helps notice and dive into which service is having failures and of what kind.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 153 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nginx_ingress_controller_requests{exported_namespace=~\"^($namespace)$\"} > 0",
       "legendFormat": "HTTP {{status}}"
      }
     ]
    },
    {
     "title": "HTTP Error",
     "type": "graph",
     "description": "The breakdown of the various HTTP status codes of the requests handled within' this period that matches the variables chosen above.\n\nThis chart helps notice and dive into which service is having failures and of what kind.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 162 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nginx_ingress_controller_requests{exported_namespace=~\"^($namespace)$\",status!~\"(1|2).*\"}) by (status) > 0",
       "legendFormat": "HTTP {{status}}"
      }
     ]
    },
    {
     "title": "HTTP Delay",
     "type": "graph",
     "description": "The breakdown of the various HTTP status codes of the requests handled within' this period that matches the variables chosen above.\n\nThis chart helps notice and dive into which service is having failures and of what kind.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 170 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nginx_ingress_controller_ingress_upstream_latency_seconds{exported_namespace=~\"^($namespace)$\"}) by (ingress)",
       "legendFormat": "{{ingress}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total log line by app / $__interval",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count_over_time({stream=~\"stdout|stderr\", namespace=~\"^($namespace)$\"} | level=\"warn\" or level=\"error\" [$__interval])) by (app)",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Messages logged by $deployment",
     "type": "logs",
     "gridPos": { "h": 9, "w": 15, "x": 9, "y": 10 },
     "targets": [
      {
       "expr": "{namespace=~\"^($namespace)$\", app=~\"$deployment\"} | logfmt |~ \"(?i)$searchable_pattern\" "
      }
     ]
    }
   ]
  },
  {
   "title": "Linkerd - $deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "deployment",
   "collapsed": true,
   "panels": [
    {
     "title": "SUCCESS RATE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (deployment)",
       "legendFormat": "deploy/{{deployment}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (le, deployment))",
       "legendFormat": "p50 deploy/{{deployment}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (le, deployment))",
       "legendFormat": "p95 deploy/{{deployment}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (le, deployment))",
       "legendFormat": "p99 deploy/{{deployment}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Events - Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overview",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (type) (count_over_time({container=\"event-exporter\"} | json | __error__=`` | metadata_namespace=~`$namespace` [$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Warnings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count_over_time({container=\"event-exporter\"} | json | __error__=`` | metadata_namespace=~`$namespace` | type=\"Warning\" [$__interval]))",
       "legendFormat": "Warning"
      }
     ]
    },
    {
     "title": "Image Pull Failed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({container=\"event-exporter\"} |= \"Error: ImagePullBackOff\" | json | __error__=`` | metadata_namespace=~`$namespace` | reason=\"Failed\"  | line_format \"{{ .message }}\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Liveness Probe Failed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({container=\"event-exporter\"} |= \"failed liveness probe\" | json | __error__=`` | metadata_namespace=~`$namespace` | reason=\"Killing\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Volume Mount Failed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({container=\"event-exporter\"} | json | __error__=`` | metadata_namespace=~`$namespace` | reason=\"FailedMount\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Scheduling Failed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({container=\"event-exporter\"} | json | __error__=`` | metadata_namespace=~`$namespace` | reason=\"FailedScheduling\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Container OOM Killed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({container=\"event-exporter\"} | json | __error__=`` | metadata_namespace=~`$namespace` | reason=\"OOMKilling\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Container Crashed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({container=\"event-exporter\"} | json | __error__=`` | metadata_namespace=~`$namespace` | reason=\"BackOff\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Pod Evicted",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({container=\"event-exporter\"} |= \"Marking for deletion Pod\" | json | __error__=`` | metadata_namespace=~`$namespace` | reason=\"TaintManagerEviction\" [$__interval]))"
      }
     ]
    },
    {
     "title": "System OOM",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({container=\"event-exporter\"} | json | __error__=`` | metadata_namespace=~`$namespace` | reason=\"SystemOOM\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Events by Source",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (source_component) (count_over_time({container=\"event-exporter\"} | json | __error__=`` | metadata_namespace=~`$namespace` [$__interval]))",
       "legendFormat": "{{source_component}}"
      }
     ]
    },
    {
     "title": "Events by Reason",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (reason) (count_over_time({container=\"event-exporter\"} | json | __error__=`` | metadata_namespace=~`$namespace` [$__interval]))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Events by Kind",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (involvedObject_kind) (count_over_time({container=\"event-exporter\"} | json | __error__=`` | metadata_namespace=~`$namespace` [$__interval]))",
       "legendFormat": "{{involvedObject_kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Для отображения метрик включите параметры мониторинга в ELMA365 enterprise: https://elma365.com/ru/help/platform/enable-monitoring-enterprise.html",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "# Disclamer\n\nДля отображения метрик включите параметры мониторинга в ELMA365 enterprise <br>\nglobal: <br>\n  ... <br>\n&nbsp;&nbsp; monitoring: <br>\n&nbsp;&nbsp;&nbsp;&nbsp; enabled: true <br>\n&nbsp;&nbsp;&nbsp;&nbsp; metrics: <br>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;enabled: true <br>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;all: true <br>\n&nbsp;&nbsp;&nbsp;&nbsp;provisioner: \"k8s\" <br>\n&nbsp;&nbsp;&nbsp;&nbsp;dashboard: <br>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;enabled: true <br>\n&nbsp;&nbsp;&nbsp;&nbsp;alerts: <br>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;enabled: false <br>\n&nbsp;&nbsp;&nbsp;&nbsp;lowcode  <br>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;metricExportEnabled: true <br>\n\nПодробнее: \nhttps://elma365.com/ru/help/platform/enable-monitoring-enterprise.html"
   }
  }
 ]
}