global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    rabbitmqQueueLength: 500
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  openshift: false
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  gatewayresources: {}
  podSecurityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  setupJobTtlSecondsAfterFinished:
images:
  worker: ci-f6afdef6
  gateway: ci-0881f5df
  setup: ci-36dec720
image:
  repository: {}
  pullSecret: {}
appconfig:
  httpProxyAddr: ''
  concurrency: 4
  forkAvailableMemorySize: 0
  skipCompilationLimits: "false"
fullnameOverride: worker
nameOverride: worker
podAnnotations: {}
podSecurityContext: {}
kubeVersion: ""
resourcesJobs: {}
resources:
  requests:
    memory: "1024Mi"
    cpu: "500m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"
gatewayresources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"
gatewayautoscaling: {}
autoscaling: {}
debugFnScriptPrioity: 1
service:
  http_port_wrk: 3000
rabbitmq:
  vhName: {}
annotations:
  ci.elma365.com/commit: "8c7047be"
  ci.elma365.com/checksum: "f6afdef6"
  ci.elma365.com/job_id: "1962837"
  ci.elma365.com/timestamp: "2024-03-01T09:47:51+00:00"
  ci.elma365.com/pipeline_id: "388462"
