global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels: {}
  annotations: {}
  kubeVersion: ""
  ingress:
    onpremiseTls:
      enabled: false
    annotations: {}
    ingressClassName: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  companies:
    - '*'
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  podSecurityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  setupJobTtlSecondsAfterFinished:
images:
  notifier: ci-a198a204
  setup: ci-fdf4ee51
image:
  repository: {}
  pullSecret: {}
appconfig:
  push:
    key: "key=AAAApqqRsOA:APA91bEerDIMXD52EzdBug1DD0jLPHpNEvK43yMoVGUUe1MhmVMcD6ajaZJ_b_ycbuWy_OUh77W8CfXdPQNoUpkhKxVFshsNqa8A5AhKtfxn2Y2aawuLO3PH0uAejyWjIaLmteC_RCFA"
  itemUpdatedConcurrencyCount: 100
  observableCollectionEventsConcurrencyCount: 100
  pushProtocol: elma365
ingress:
  annotations: {}
autoscaling: {}
nameOverride: notifier
podSecurityContext: {}
podAnnotations: {}
kubeVersion: ""
resourcesJobs: {}
resources: {}
rabbitmq: {}
annotations:
  ci.elma365.com/commit: "e0019a8b"
  ci.elma365.com/checksum: "fdf4ee51"
  ci.elma365.com/job_id: "1946273"
  ci.elma365.com/timestamp: "2024-02-14T05:32:36+00:00"
  ci.elma365.com/pipeline_id: "386116"
