{
 "title": "worker onpremise dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up, region)" } },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(up{job=~\"worker.*\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(up{job=~\"worker.*\",cluster=~\"$cluster\",namespace=~\"$namespace\"})"
    }
   },
   {
    "name": "company",
    "label": "company",
    "query": {
     "query": "query_result(worker_execute_scripts_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\"})"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "postgresql query execution time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (rate(elma365_common_postgresql_query_execution_time_histogram_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "postgresql query total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(company) (topk(5, rate(elma365_common_postgresql_query_total_count{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[5m])))",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
     "legendFormat": "Resident {{namespace}} {{pod}}"
    },
    {
     "expr": "process_virtual_memory_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
     "legendFormat": "Virtual {{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[5m]) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "forks / pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (cluster, namespace) (worker_forks_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\"})",
     "legendFormat": "FORKs {{namespace}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (cluster, namespace) (up{cluster=~\"^($cluster)$\",job=\"worker\"})",
     "legendFormat": "PODs {{namespace}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "http_server_request_duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(http_server_request_duration_seconds_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[1m])) by (le, cluster, namespace, pod))",
     "legendFormat": "p50 {{namespace}} {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(http_server_request_duration_seconds_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[1m])) by (le, cluster, namespace, pod))",
     "legendFormat": "p95 {{namespace}} {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(http_server_request_duration_seconds_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[1m])) by (le, cluster, namespace, pod))",
     "legendFormat": "p99 {{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "unknown errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  increase(worker_execution_unknown_errors_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\", company=~\"^($company)$\"}[$__range])\r\n) by (namespace, company) > 0"
    }
   ]
  },
  {
   "title": "compilation errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    increase(worker_compilation_errors_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\", company=~\"^($company)$\"}[$__rate_interval])\r\n) by (namespace, company) > 0"
    }
   ]
  },
  {
   "title": "compilation system errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    increase(worker_compilation_system_errors_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\", company=~\"^($company)$\"}[$__rate_interval])\r\n) by (namespace, company) > 0"
    }
   ]
  },
  {
   "title": "execute scripts total",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(\r\n    increase(worker_execute_scripts_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\", company=~\"^($company)$\"}[$interval])\r\n) by (namespace, company, source) > 0",
     "legendFormat": "{{namespace}} {{company}} {{source}}"
    }
   ]
  },
  {
   "title": "compilation timeout errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    increase(worker_compilation_timeout_errors_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\", company=~\"^($company)$\"}[$__rate_interval])\r\n) by (namespace, company)"
    }
   ]
  },
  {
   "title": "execution system errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(\r\n    increase(worker_execution_system_errors_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\", company=~\"^($company)$\"}[$__range])\r\n) by (namespace, company) > 0",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "execution timeout errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    increase(worker_execution_timeout_errors_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\", company=~\"^($company)$\"}[$__range])\r\n) by (namespace, company) > 0"
    }
   ]
  },
  {
   "title": "active scripts / $interval - top 5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(\r\n    increase(worker_execute_scripts_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$interval])\r\n) by (namespace, company, source))",
     "legendFormat": "{{namespace}} {{company}} {{source}}"
    },
    {
     "expr": "topk(5, sum by (namespace, company) (increase(worker_execute_scripts_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$interval])))",
     "legendFormat": "{{namespace}} {{company}} ALL"
    }
   ]
  },
  {
   "title": "total scripts / $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, source) (increase(worker_execute_scripts_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\"}[$interval]))",
     "legendFormat": "{{namespace}} {{source}} - TOTAL"
    },
    {
     "expr": "sum by (namespace) (increase(worker_execute_scripts_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\"}[$interval]))",
     "legendFormat": "{{namespace}} - TOTAL"
    }
   ]
  },
  {
   "title": "worker gateway http server request total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": " topk(5, sum by(company) (rate(worker_gateway_http_server_requests_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "worker gateway http server request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": " topk(5, sum by(company) (rate(worker_gateway_http_server_request_duration_seconds_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "script compile time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum by (le, namespace, company, source) (rate(worker_script_compile_time_histogram_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\", company=~\"^($company)$\"}[$__rate_interval]))\n)",
     "legendFormat": "p95 {{namespace}} {{company}} {{source}}"
    }
   ]
  },
  {
   "title": "script execution time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(5, \r\n  histogram_quantile(0.95, sum(rate(worker_script_execution_time_histogram_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\", company=~\"^($company)$\"}[$__rate_interval])) by (le, namespace, company, source))\r\n) > 0",
     "legendFormat": "p95 {{cluster}} {{namespace}} {{company}} {{source}}"
    }
   ]
  },
  {
   "title": "GO STATS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "process memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
       "legendFormat": "Resident {{namespace}} {{pod}}"
      },
      {
       "expr": "process_virtual_memory_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
       "legendFormat": "Virtual {{namespace}} {{pod}}"
      }
     ]
    },
    {
     "title": "process memory deriv",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval])",
       "legendFormat": "Resident {{cluster}} {{namespace}} {{pod}}"
      },
      {
       "expr": "deriv(process_virtual_memory_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
       "legendFormat": "Virtual {{cluster}} {{namespace}} {{pod}}"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
       "legendFormat": "Bytes allocated {{cluster}} {{namespace}} {{pod}}"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[30s])",
       "legendFormat": "Alloc rate {{cluster}} {{namespace}} {{pod}}"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
       "legendFormat": "Stack inuse {{cluster}} {{namespace}} {{pod}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
       "legendFormat": "Heap inuse {{cluster}} {{namespace}} {{pod}}"
      }
     ]
    },
    {
     "title": "go memstats deriv",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval])",
       "legendFormat": "Bytes allocated {{cluster}} {{namespace}} {{pod}}"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval])",
       "legendFormat": "Alloc rate {{cluster}} {{namespace}} {{pod}}"
      },
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval])",
       "legendFormat": "Stack inuse {{cluster}} {{namespace}} {{pod}}"
      },
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval])",
       "legendFormat": "Heap inuse {{cluster}} {{namespace}} {{pod}}"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
       "legendFormat": "{{cluster}} {{namespace}} {{pod}}"
      }
     ]
    },
    {
     "title": "open fds deriv",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "deriv(process_open_fds{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval])",
       "legendFormat": "{{cluster}} {{namespace}} {{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
       "legendFormat": "{{cluster}} {{namespace}} {{pod}}"
      }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=~\"1\", cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
       "legendFormat": "{{cluster}} {{namespace}} {{pod}} quantile"
      }
     ]
    }
   ]
  }
 ]
}