{
 "title": "event-bus dashboard",
 "description": "Process status published by Go prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up, region)" } },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(up{job=~\"event-bus\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(up{job=~\"event-bus\",cluster=~\"$cluster\",namespace=~\"$namespace\"})"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "postgresql query execution time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (rate(elma365_common_postgresql_query_execution_time_histogram_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "postgresql query total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(company) (topk(5, rate(elma365_common_postgresql_query_total_count{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[5m])))",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
     "legendFormat": "Resident {{namespace}} {{pod}}"
    },
    {
     "expr": "process_virtual_memory_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
     "legendFormat": "Virtual {{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"^($namespace)$\", pod=~\"^($pod)$\", container=~\"event-bus*\"}[5m]) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
     "legendFormat": "Bytes allocated {{cluster}} {{namespace}} {{pod}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[30s])",
     "legendFormat": "Alloc rate {{cluster}} {{namespace}} {{pod}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "Stack inuse {{cluster}} {{namespace}} {{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "Heap inuse {{cluster}} {{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "Resident {{cluster}} {{namespace}} {{pod}}"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "Virtual {{cluster}} {{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "Bytes allocated {{cluster}} {{namespace}} {{pod}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "Alloc rate {{cluster}} {{namespace}} {{pod}}"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "Stack inuse {{cluster}} {{namespace}} {{pod}}"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "Heap inuse {{cluster}} {{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "http server request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(http_server_request_duration_seconds_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[1m])) by (le, cluster, namespace, pod))",
     "legendFormat": "p50 {{cluster}} {{namespace}} {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(http_server_request_duration_seconds_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[1m])) by (le, cluster, namespace, pod))",
     "legendFormat": "p95{{cluster}} {{namespace}} {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(http_server_request_duration_seconds_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[1m])) by (le, cluster, namespace, pod))",
     "legendFormat": "p99 {{cluster}} {{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
     "legendFormat": "{{cluster}} {{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
     "legendFormat": "{{cluster}} {{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "response sizes for requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(http_server_response_size_bytes_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}[1m])) by (le, cluster, namespace, pod))"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=~\"1\", cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", pod=~\"^($pod)$\"}",
     "legendFormat": "{{cluster}} {{namespace}} {{pod}} quantile"
    }
   ]
  }
 ]
}