{{- $dot := . }}
{{- if and .Values.global.workerPoolCfg .Values.global.workerPoolCfg.pools (gt (len .Values.global.workerPoolCfg.pools) 0) }}
{{- range $poolKey, $poolValue := .Values.global.workerPoolCfg.pools }}

  {{- $nameParams := dict "GlobalContext" $dot "poolKey" $poolKey }}
  {{- $name := include "worker.pool.name" $nameParams }}
  {{- $queueName := printf "script.pool.%s" $poolKey }}
  {{- $autoscaling := $poolValue.autoscaling | default $dot.Values.global.autoscaling }}
  {{- $localContext := dict "name" $name "queueName" $queueName "defaultPool" false "poolKey" $poolKey "autoscaling" $autoscaling }}
  {{- $params := dict "GlobalContext" $dot "LocalContext" $localContext "Chart" $dot.Chart "Release" $dot.Release "Values" $dot.Values "Capabilities" $dot.Capabilities }}

{{- template "worker.deployment" $params }}
---
{{- template "worker.service" $params}}
---
{{- if $dot.Values.global.helmLibrary }}
{{- include "helm-library.hpa-worker" $params }}
---
{{- include "helm-library.keda-worker" $params }}
---
{{- include "helm-library.servicemonitor-worker" $params }}
{{- end }}

{{- end }}
{{- end }}
