global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
images:
  service: ci-4a445b94
  setup: develop
image:
  repository: {}
  pullSecret: {}
nameOverride: template-mapper
podAnnotations: {}
podSecurityContext: {}
autoscaling: {}
resourcesJobs: {}
resources:
  requests:
    memory: "384Mi"
    cpu: "150m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
template-mapper:
  labels:
    app: template-mapper
ingress:
  annotations: {}
  gzip:
    enabled: true
    compLevel: 5
    minLength: 1024
annotations:
  ci.elma365.com/commit: "2455e516"
  ci.elma365.com/checksum: "4a445b94"
  ci.elma365.com/job_id: "1946023"
  ci.elma365.com/timestamp: "2024-02-14T05:31:44+00:00"
  ci.elma365.com/pipeline_id: "386104"
