global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    rabbitmqQueueLength: 500
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  openshift: false
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  gatewayresources: {}
  podSecurityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  setupJobTtlSecondsAfterFinished:
images:
  worker: ci-6c367e35
  gateway: ci-a9f9f080
  setup: ci-d0eb17cd
image:
  repository: {}
  pullSecret: {}
appconfig:
  httpProxyAddr: ''
  concurrency: 4
  forkAvailableMemorySize: 0
  skipCompilationLimits: "false"
fullnameOverride: worker
nameOverride: worker
podAnnotations: {}
podSecurityContext: {}
kubeVersion: ""
resourcesJobs: {}
resources:
  requests:
    memory: "1024Mi"
    cpu: "500m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"
gatewayresources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"
gatewayautoscaling: {}
autoscaling: {}
debugFnScriptPrioity: 1
service:
  http_port_wrk: 3000
rabbitmq:
  vhName: {}
networkPolicy:
  allowIPLocalDns:
    - 169.254.25.10/32
    - 169.254.20.10/32
    - 10.96.128.2/32
  allowAllIPexcept:
    - 10.96.0.0/16
    - 10.100.0.0/16
    - 10.111.0.0/16
    - 10.222.0.0/16
  allowNamespaceName:
    - elma365-adds
    - elma365-applets
  allowIngressLabel:
    app.kubernetes.io/name: "ingress-nginx"
annotations:
  ci.elma365.com/commit: "52956f0c"
  ci.elma365.com/checksum: "6c367e35"
  ci.elma365.com/job_id: "2158856"
  ci.elma365.com/timestamp: "2024-05-07T14:59:44+03:00"
  ci.elma365.com/pipeline_id: "418665"
