{{- if and .Values.global.rbac.create (not (lookup "rbac.authorization.k8s.io/v1" "Role" .Release.Namespace "modify-secrets")) }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
{{- end }}
