{
 "title": "main front-api dashboard",
 "description": "Process status published by Go prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": "label_values(up, region)" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "query_result(up{job=~\"main\",cluster=~\"$cluster\"})"
   },
   {
    "name": "company",
    "label": "company",
    "query": "label_values(front_api_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}, company)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, \n  histogram_quantile(0.95, sum(irate(front_api_request_duration_seconds_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$__rate_interval])) by (le, company, namespace))\n)",
     "legendFormat": "{{company}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Request total / $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,\n  sum by (company, namespace) ( \n    increase(front_api_requests_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$interval])\n  ) +\n  sum by (company, namespace) (\n    increase(worker_gateway_http_server_requests_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$interval])\n  )\n)",
     "legendFormat": "TOTAL {{company}}"
    },
    {
     "expr": "topk(10, sum by (company, namespace) ( \n  increase(worker_gateway_http_server_requests_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$interval]) \n))",
     "legendFormat": "SERVER {{company}}"
    },
    {
     "expr": "topk(10, sum by (company, namespace) ( \n  increase(front_api_requests_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$interval])\n))",
     "legendFormat": "FRONT {{company}}"
    }
   ]
  },
  {
   "title": "Response sizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, \r\n  max by (namespace, company) (rate(front_api_response_size_bytes_sum{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$__rate_interval]))\r\n)",
     "legendFormat": "{{company}} {{namespace}}"
    }
   ]
  }
 ]
}