{
 "title": "main web-api dashboard",
 "description": "Process status published by Go prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": "label_values(up, region)" },
   {
    "name": "namespace",
    "query": "query_result(up{job=~\"main\",cluster=~\"$cluster\"})"
   },
   {
    "name": "company",
    "label": "company",
    "query": "label_values(web_api_http_server_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\", job=\"main\"}, company)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, \r\n  histogram_quantile(0.95, sum(irate(web_api_http_server_request_duration_seconds_bucket{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$__rate_interval])) by (le, company, namespace))\r\n)",
     "legendFormat": "{{namespace}} {{company}}"
    }
   ]
  },
  {
   "title": "Request total / $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (company, namespace) ( \n  increase(web_api_http_server_requests_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$interval]) \n))",
     "legendFormat": "{{namespace}} {{company}}"
    }
   ]
  },
  {
   "title": "Response sizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, \r\n  max by (namespace, company) (rate(web_api_http_server_response_size_bytes_sum{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$__rate_interval]))\r\n)",
     "legendFormat": "{{namespace}} {{ company}}"
    }
   ]
  }
 ]
}