global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels:
    event-producer: "true"
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    rabbitmqQueueLength: 500
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  setupJobTtlSecondsAfterFinished:
images:
  diskjockey: ci-9a5d59ea
  setup: ci-d6885c27
image:
  repository: {}
  pullSecret: {}
nameOverride: diskjockey
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
kubeVersion: ""
resourcesJobs: {}
resources:
  requests:
    memory: "256Mi"
    cpu: "150m"
  limits:
    memory: "1024Mi"
    cpu: "700m"
autoscaling: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
rabbitmq:
  vhName: {}
annotations:
  ci.elma365.com/commit: "1722839e"
  ci.elma365.com/checksum: "d6885c27"
  ci.elma365.com/job_id: "3081013"
  ci.elma365.com/timestamp: "2025-03-27T06:09:50+00:00"
  ci.elma365.com/pipeline_id: "557279"
