global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  ingress:
    onpremiseTls:
      enabled: false
    annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: Recreate
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  startupProbe:
    httpGet:
      path: /healthz
      port: http
    failureThreshold: 180
    periodSeconds: 10
  podSecurityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
images:
  service: ci-d39a6980
  setup: develop
image:
  repository: {}
  pullSecret: {}
nameOverride: messenger-other
podSecurityContext: {}
podAnnotations: {}
autoscaling: {}
resourcesJobs: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
messenger-other:
  labels:
    app: messenger-other
ingress:
  annotations: {}
  gzip:
    enabled: true
    compLevel: 5
    minLength: 1024
annotations:
  ci.elma365.com/commit: "602fa479"
  ci.elma365.com/checksum: "d39a6980"
  ci.elma365.com/job_id: "1946276"
  ci.elma365.com/timestamp: "2024-02-14T05:33:34+00:00"
  ci.elma365.com/pipeline_id: "386113"
