apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "diskjockey.name" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "diskjockey.labels" . | nindent 4 }}
data:
    # Rabbitmq
    ELMA365_RABBITMQ_USER: {{ template "diskjockey.rmquser" . }}