global:
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  startupProbe: {}
  gotenberg:
    livenessProbe:
      httpGet:
        path: /ping
        port: 4000
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 2
      failureThreshold: 1
      successThreshold: 1
    readinessProbe:
      httpGet:
        path: /ping
        port: 4000
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 2
      failureThreshold: 1
      successThreshold: 1
    startupProbe: {}
  podSecurityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  setupJobTtlSecondsAfterFinished:
images:
  setup: ci-654e5225
  gateway: ci-37601166
  dotenberg: ci-0f82c1ef
image:
  repository: {}
  pullSecret: {}
nameOverride: convertik
podSecurityContext: {}
podAnnotations: {}
kubeVersion: ""
autoscaling: {}
resourcesJobs: {}
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "555Mi"
    cpu: "555m"
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
gotenberg:
  resources: {}
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}
logging:
  default: Information
  microsoft: Warning
rabbitmq:
  vhName: {}
retryTime: 60
annotations:
  ci.elma365.com/commit: "917f4b1d"
  ci.elma365.com/checksum: "654e5225"
  ci.elma365.com/job_id: "1946146"
  ci.elma365.com/timestamp: "2024-02-14T05:30:47+00:00"
  ci.elma365.com/pipeline_id: "386109"
