apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Chart.Name }}-setup-{{ .Values.images.setup }}"
  labels:
  {{- include "event-bus.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
spec:
  backoffLimit: {{ .Values.global.backoffLimit }}
{{- if .Values.global.setupJobTtlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.global.setupJobTtlSecondsAfterFinished }}
{{- end }}
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
      annotations:
        linkerd.io/inject: disabled
    spec:
      {{- if .Values.global.helmLibrary }}
      securityContext:
        {{- include "helm-library.job.podSecurityContext" . | nindent 8 }}
      {{- include "helm-library.deployment.scheduling" . | indent 6 }}
      {{- end }}
      restartPolicy: OnFailure
      imagePullSecrets:
        {{- if .Values.image.pullSecret }}
        {{- range .Values.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- else }}
        {{- range .Values.global.image.pullSecret }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: setup
          image: "{{ .Values.image.repository | default .Values.global.image.repository }}/elma365/event_bus/setup:{{ .Values.images.setup }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: ELMA365_RABBITMQ_EVENT_BUS_USER
              value: {{ template "event-bus.rmquser" . }}
            - name: ELMA365_RABBITMQ_EVENT_BUS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eventbus
                  key: rabbitmq_password
          envFrom:
            - configMapRef:
                name: elma365-env-config
                optional: true
            - secretRef:
                name: elma365-db-connections
                optional: true
        {{- if .Values.global.helmLibrary }}
          {{- include "helm-library.job.resources" . | indent 10 }}
        {{- end }}
