{{- define "helm-library.deployment.env" }}
- name: GOMEMLIMIT
  value: {{ include "gomemlimit" . | quote }}
- name: GOMAXPROCS
  value: {{ include "gomaxprocs" . | toString | toYaml }}
{{- end }}

{{- define "helm-library.deployment.env-worker-gateway" }}
- name: GOMEMLIMIT
  value: {{ include "gomemlimit-worker-gateway" . | quote }}
- name: GOMAXPROCS
  value: {{ include "gomaxprocs-worker-gateway" . | toString | toYaml }}
{{- end }}
