{
 "title": "Kubernetes: api/kubelet perfomance",
 "description": "Kubernetes: api/kubelet perfomance",
 "tags": [
  "kubelet",
  "kube-api"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "label_values(up, region)" }
  ]
 },
 "panels": [
  {
   "title": "API Server Requests (Req/Sec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[2m])) by (region)",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "API Server Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(apiserver_request_latencies_sum / apiserver_request_latencies_count) by (region)",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Kube Pleg relist duration | $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,rate(kubelet_pleg_relist_duration_seconds_bucket{region=\"$cluster\", node=~\".+\"}[5m]))",
     "legendFormat": "{{ region }} | {{ node }}"
    }
   ]
  },
  {
   "title": "Kubelet Pod Start Latency",
   "type": "graph",
   "description": "Latency in microseconds for a single pod to go from pending to running. Broken down by podname.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_pod_start_latency_microseconds_sum{region=~\"$cluster\", node=~\".+\"}[5m]) / rate(kubelet_pod_start_latency_microseconds_count{region=~\"$cluster\", node=~\".+\"}[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Creating Rate of Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_running_pod_count{region=~\"$cluster\", node=~\".+\"}[2m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Running Pods Trands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_pod_count{region=~\"$cluster\", node=~\".+\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Creating Rate of Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_running_container_count{region=~\"$cluster\", node=~\".+\"}[2m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Running Containers Trands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_container_count{region=~\"$cluster\", node=~\".+\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}