global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: true
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: true
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
images:
  service: ci-c5cad125
image:
  repository: {}
  pullSecret: {}
nameOverride: registrator
podAnnotations: {}
podSecurityContext: {}
kubeVersion: ""
resourcesJobs: {}
resources: {}
nodeSelector: {}
tolerations: []
autoscaling: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
registrator:
  labels:
    app: registrator
annotations:
  ci.elma365.com/commit: "b1cd7982"
  ci.elma365.com/checksum: "c5cad125"
  ci.elma365.com/job_id: "2146959"
  ci.elma365.com/timestamp: "2024-04-25T10:39:21+00:00"
  ci.elma365.com/pipeline_id: "416626"
