name: 🔄 ArgoCD Force Sync

on:
  workflow_dispatch:  # ручной запуск из UI
  push:
    branches: [main]  # можно также: [release/**]

jobs:
  sync:
    name: 🔁 Force ArgoCD Sync
    runs-on: ubuntu-latest

    steps:
      - name: 🔐 Вход в ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} \
            --username ${{ secrets.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure

      - name: 🔄 Синхронизация elma365
        run: |
          argocd app sync elma365 --prune --force --replace --insecure

      - name: 🧪 Проверка статуса приложений
        run: |
          argocd app wait elma365 --health --sync --timeout 300
          argocd app wait elma365-dbs --health --sync --timeout 300
