{
 "title": "main limits",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "label_values(up, region)" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "query_result(up{job=~\"main\",cluster=~\"$cluster\"})"
   },
   {
    "name": "company",
    "label": "company",
    "query": {
     "query": "label_values(front_api_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\"},company)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "heavy query top 10",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (company, namespace) ( \n  increase(limits_filter_heavy_executed_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$interval]) \n))",
     "legendFormat": "{{company}} {{namespace}}"
    }
   ]
  },
  {
   "title": "simple query top 10",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (company, namespace) ( \n  increase(limits_filter_simple_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$interval]) \n))",
     "legendFormat": "{{company}} {{namespace}}"
    }
   ]
  },
  {
   "title": "limits rejected",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, company, resourceId) (increase(limits_common_rejected_requests_total{cluster=~\"^($cluster)$\", namespace=~\"^($namespace)$\", company=~\"^($company)$\"}[$interval]))",
     "legendFormat": "{{namespace}} {{company}} | {{resourceId}}"
    }
   ]
  }
 ]
}